# Generated by Django 5.2.7 on 2026-09-10 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutoPostprocessing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.CharField(max_length=100)),
                ('qr_data', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
                ('pre_id', models.IntegerField(blank=True, null=True)),
                ('batch_id', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'auto_postprocessing',
                'ordering': ['-id'],
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AutoPreprocessing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.CharField(max_length=100)),
                ('machine_name', models.CharField(max_length=50)),
                ('qr_data', models.CharField(max_length=100)),
                ('pervious_status', models.CharField(max_length=20)),
                ('batch_id', models.CharField(blank=True, max_length=50, null=True)),
                ('batch_size', models.IntegerField(blank=True, null=True)),
                ('slot_no', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'auto_preprocessing',
                'ordering': ['-id'],
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CiPostprocessing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.CharField(max_length=100)),
                ('qr_data', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
                ('pre_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ci_postprocessing',
                'ordering': ['-id'],
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CiPreprocessing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.CharField(max_length=100)),
                ('machine_name', models.CharField(max_length=50)),
                ('qr_data', models.CharField(max_length=100)),
                ('pervious_status', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'ci_preprocessing',
                'ordering': ['-id'],
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HeliumPostprocessing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.CharField(max_length=100)),
                ('qr_data', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
                ('pre_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'helium_postprocessing',
                'ordering': ['-id'],
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HeliumPreprocessing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.CharField(max_length=100)),
                ('machine_name', models.CharField(max_length=50)),
                ('qr_data', models.CharField(max_length=100)),
                ('pervious_status', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'helium_preprocessing',
                'ordering': ['-id'],
                'abstract': False,
                'managed': False,
            },
        ),
    ]
