# Generated by Django 5.2.7 on 2026-09-11 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracebility', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatorAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machines', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='operator_assignment', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Access Control - Operator Station',
                'verbose_name_plural': 'Access Control - Operator Stations',
                'db_table': 'operator_assignment',
                'ordering': ['user__username'],
                'managed': True,
            },
        ),
    ]
